import "./globals.css";

import React from "react";
import Providers from "@/components/providers";
import AppShellLayout from "@/components/shellLayout";


export const metadata = {
  title: "NoteBook App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <AppShellLayout>{children}</AppShellLayout>
        </body>
      </html>
    </Providers>
  );
}
